name: Build LaTeX to PDF

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build PDF
        run: sudo apt-get install texlive-latex-base && pdflatex main.tex
      - name: Output PDF
        uses: actions/upload-artifact@v2
        with:
          name: main.pdf
          path: main.pdf
