name: Build LaTeX to PDF and Create Release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base

      - name: Build PDF
        run: pdflatex main.tex

      - name: Rename PDF
        run: mv main.pdf output.pdf

      - name: Upload PDF as Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: output.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
